### ISSUE TITLE
Tes Build error

### ISSUE THREAD

**Issue by XeRA0** [KasperGameDev/Dialogue-Editor-Tutorial#1]
HI
i wanted to test build the project and i got this 
https://i.imgur.com/dnAnLwJ.png
the project is untouched tried the zip file download and the git clone methods same errors

**Comment by KasperGameDev** [comment]
Ye.
for some reason it is still trying to build the scripts in the editor folder.
i fix it with #if UNITY_EDITOR for now.
you should now be able to build.

Thanks for bringing this to my attention.

**Comment by XeRA0** [comment]
Yes its working now cheers mate
