### ISSUE TITLE
a question 

### ISSUE THREAD

**Issue by RandomOtter** [KasperGameDev/Dialogue-Editor-Tutorial#6]
Hey Kasper ,

How do you think should i approach a back button for the dialogue editor  ?

i tried RemoveAt and a foreach methods but or they break or not working at all any idea of how should i approach this ?

**Comment by KasperGameDev** [comment]
When you read the dialogue data
Save the last dialogue node so when you click go back it go to that dialogue node.
You can add all dialogue node in to a list as you go and when you go back look at the last dialogue node and go to that one and remove it from the list.

Hop this helps.

**Comment by KasperGameDev** [comment]
When you read the dialogue data
Save the last dialogue node so when you click go back it go to that dialogue node.
You can add all dialogue node in to a list as you go and when you go back look at the last dialogue node and go to that one and remove it from the list.

Hop this helps.
